// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU8V_7--i5kSplpbJkId1gVhRXoKDe8iw',
    appId: '1:338070517686:web:f113675f5a67e3e1dc7317',
    messagingSenderId: '338070517686',
    projectId: 'sampark-my',
    authDomain: 'sampark-my.firebaseapp.com',
    storageBucket: 'sampark-my.firebasestorage.app',
    measurementId: 'G-CFM2JBSKBR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbyvQ0VuA4r6ttm8jse4RXvKLhobrjDg4',
    appId: '1:338070517686:android:0c9663da95efddd8dc7317',
    messagingSenderId: '338070517686',
    projectId: 'sampark-my',
    storageBucket: 'sampark-my.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv8Q_Y5eNzRFcJsyTB37TM9A1yhtvZvt0',
    appId: '1:338070517686:ios:51ef82cd11273510dc7317',
    messagingSenderId: '338070517686',
    projectId: 'sampark-my',
    storageBucket: 'sampark-my.firebasestorage.app',
    iosBundleId: 'com.example.myChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv8Q_Y5eNzRFcJsyTB37TM9A1yhtvZvt0',
    appId: '1:338070517686:ios:51ef82cd11273510dc7317',
    messagingSenderId: '338070517686',
    projectId: 'sampark-my',
    storageBucket: 'sampark-my.firebasestorage.app',
    iosBundleId: 'com.example.myChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAU8V_7--i5kSplpbJkId1gVhRXoKDe8iw',
    appId: '1:338070517686:web:adfe0adbc0560531dc7317',
    messagingSenderId: '338070517686',
    projectId: 'sampark-my',
    authDomain: 'sampark-my.firebaseapp.com',
    storageBucket: 'sampark-my.firebasestorage.app',
    measurementId: 'G-ZB6T9MQRHG',
  );
}
